#!/usr/bin/env bash

set -e

if [[ -n "${DEBUG_MODE}" ]]; then
  set -x
fi

function usage() {
  echo -n \
    "Usage: $(basename "$0")
Build application for staging or a release.
"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  if [[ "${1:-}" == "--help" ]]; then
    usage
  else
    # create .gradle with correct user permissions
    # docker daemon may otherwise create this directory with root ownership
    mkdir -p .gradle build/libs

    # if mounting the hosts cache folder, gradle inside the container will try and
    # acquire a file lock that the host machine may already be holding. this will
    # result in the container hanging indefinitely. stopping any existing daemons
    # on the host is the simplest way to 'solve' this issue
    if command -v java &>/dev/null; then
      ./gradlew --stop
    fi

    chmod +x ./gradlew

    CI="${CI:-}" docker-compose -f docker-compose.ci.yml \
      run --rm gradle
  fi
fi
