name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Caches Gradle dependencies and wrappers
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-2
            ~/.gradle/wrapper/dists
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts', '**/gradle.properties', '**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run cibuild script
        id: exec
        run: ./scripts/cibuild

      - name: Cleanup Gradle Cache
        run: |
          sudo rm -f ~/.gradle/caches/modules-2/modules-2.lock
          sudo rm -f ~/.gradle/caches/modules-2/gc.properties

# TODO:
#      - name: Upload the built artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: ${{ steps.exec.outputs.jar }}
#          path: build/libs/${{ steps.exec.outputs.jar }}
#          if-no-files-found: error
