name: CI

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Caches Gradle dependencies and wrappers
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-2
            ~/.gradle/wrapper/dists
            ./.gradle/paperweight_cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts', '**/gradle.properties', '**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run cibuild script
        id: exec
        run: ./scripts/cibuild

      - name: Cleanup Gradle Cache
        run: |
          sudo rm -f ~/.gradle/caches/modules-2/modules-2.lock
          sudo rm -f ~/.gradle/caches/modules-2/gc.properties

      - name: Rename build files
        run: |
          pushd build/libs
          cp ${{ steps.exec.outputs.paperclip }} PaperX-paperclip.jar
          cp ${{ steps.exec.outputs.bundler }} PaperX-bundler.jar
          popd

      - name: Create release if this is a tagged workflow
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          artifacts: build/libs/PaperX-paperclip.jar
          name: PaperX ${{ steps.exec.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}